package modelos;
// Generated 11/10/2019 10:10:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private String idMarca;
     private String descripcion;
     private Set productos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(String idMarca, String descripcion) {
        this.idMarca = idMarca;
        this.descripcion = descripcion;
    }
    public Marca(String idMarca, String descripcion, Set productos) {
       this.idMarca = idMarca;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public String getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(String idMarca) {
        this.idMarca = idMarca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


